### ISSUE TITLE
Reward listener's reward is always zero

### ISSUE THREAD

**Issue by AiwNexT** [BitBurst-GmbH/bitlabs-android-library#12]
I'm using the latest version of BitLabs library (3.0.3). In the dashboard, I see a lot of survey completions. However, not a single reward is given to users. Actually, the reward listener's reward value is always zero. I checked the documentation a lot of times to exclude the possibility of a mistake during implementation. However, it seems like the issue is not here. Could somebody please take a look at this issue?

**Comment by AiwNexT** [comment]
@omaRaad @ben-asb Could you take a loot at this please?

**Comment by omaRaad** [comment]
@AiwNexT I'm sorry for the late reply. I was on holiday.

Please show me your implementation code

**Comment by AiwNexT** [comment]
@omaRaad It's ok. No worries!

Here is the implementation snippet:
```
class BitLabsHelper(
    globalIdProvider: IGlobalIdProvider,
    deviceIdProvider: IDeviceIdProvider,
    authUseCase: AuthUseCase,
    adsRewardHelper: IAdsRewardHelper,
    rewardStatusProvider: IRewardStatusProvider,
    crashlyticsHelper: CrashlyticsHelper,
    analyticsHelper: AnalyticsHelper
) : ABRewardedAdsHelper(
    globalIdProvider,
    deviceIdProvider,
    authUseCase,
    adsRewardHelper,
    rewardStatusProvider,
    crashlyticsHelper,
    analyticsHelper,
) {

    private var available: Boolean = false
        set(value) {
            field = value
            didAvailabilityChange(value)
        }

    override val sourceType: TokenSourceType = TokenSourceType.SURVEYS
    override val rewardSource: IRewardSource = AdProvider.BITLABS

    override fun performInit(activity: Activity) {
        getUserIdentificationIds()
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe({ identification ->
                BitLabs.init(
                    activity,
                    Secrets.BITLABS_TOKEN,
                    identification.deviceId,
                )
                setUpRewardsHandling()
                available = true
            }, {
                crashlyticsHelper.log(it)
                available = false
            })
    }

    private fun setUpRewardsHandling() {
        BitLabs.setOnRewardListener { tokens ->
            rewardUser(
                reward = tokens.toLong(),
                onUserRewarded = {
                    analyticsHelper.didReceiveBitLabsReward()
                },
            )
        }
    }

    override fun show(activity: Activity) {
        BitLabs.launchOfferWall(activity)
        analyticsHelper.didOpenBitLabs()
    }

    override fun isAvailable(): Boolean {
        return available
    }

    override fun reportUnavailability() {}
}
```

I use the kind of implementation for all the ad provides inside the app (Pollfish, AdGem, AdGate media, ayeT-Studios, OfferToro). So stuff like `getUserIdentificationIds()` and in-app rewards logic works well. The method `rewardUser` simply checks whether the reward is not 0 and if it's not, then it adds the reward amount to the user balance & executes the `onUserRewarded` callback.

**Comment by omaRaad** [comment]
Okay @AiwNexT, I want you to test something on you end.

1. In the `setOnRewardListener`, please log the token before calling `rewardUser`, and let me know what it records.
2. Also, do you know that the **OnRewardListener** is called specifically when you close the whole Offerwall? so keep that in mind while testing.

**Comment by AiwNexT** [comment]
@omaRaad Sure, I already did such kind of testing before opening this issue's ticket. 
Basically, each time I close the offerwall, the `setOnRewardListener`'s callback is triggered (which is fine). The value I get is always 0.0 (since it's a `Float` value). And it's not just me. I use analytics to see whether users receive their rewards or not. All of my app's users receive 0.0 all the time (I mean, even if there was a completed survey and there is a data indicating a survey completion in the dashboard).

**Comment by omaRaad** [comment]
@AiwNexT I will check if the issue persists on all apps, but for the time being, please use the server-to-server callback for rewards

**Comment by AiwNexT** [comment]
@omaRaad We don't have a possibility to switch to the server-to-server callbacks. So we would be very happy if you check the other apps.

**Comment by omaRaad** [comment]
Hey @AiwNexT, I tested the onReward and didn't have any issue. I could get the reward normally.

**Comment by AiwNexT** [comment]
Hi @omaRaad, sorry for the late reply. I've just updated to the latest version and it seems like the issue is gone. Thanks for your help!

**Comment by omaRaad** [comment]
@AiwNexT, that's great to hear! Just for my info, did you update from [3.0.3](https://github.com/BitBurst-GmbH/bitlabs-android-library/releases/tag/3.0.3) or from an earlier one?

**Comment by AiwNexT** [comment]
@omaRaad The previous one we had was 3.0.2
