### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by duff627** [BitBurst-GmbH/bitlabs-android-library#36]
* What went wrong:
Execution failed for task ':app:mapxxx_testDebugSourceSetPaths'.
> Could not resolve all files for configuration ':app:xxx_testDebugRuntimeClasspath'.
   > Could not resolve com.github.BitBurst-GmbH.bitlabs-android-library:core:3.2.2.
     Required by:
         project :app
      > Could not resolve com.github.BitBurst-GmbH.bitlabs-android-library:core:3.2.2.
         > Could not get resource 'https://jitpack.io/com/github/BitBurst-GmbH/bitlabs-android-library/core/3.2.2/core-3.2.2.pom'.
            > Could not GET 'https://jitpack.io/com/github/BitBurst-GmbH/bitlabs-android-library/core/3.2.2/core-3.2.2.pom'.
               > Read timed out
   > Could not resolve com.github.BitBurst-GmbH.bitlabs-android-library:core:3.2.2.
     Required by:
         project :app > xxxxx:2.5.4
      > Could not resolve com.github.BitBurst-GmbH.bitlabs-android-library:core:3.2.2.
         > Could not get resource 'https://jitpack.io/com/github/BitBurst-GmbH/bitlabs-android-library/core/3.2.2/core-3.2.2.pom'.
            > Could not GET 'https://jitpack.io/com/github/BitBurst-GmbH/bitlabs-android-library/core/3.2.2/core-3.2.2.pom'.
               > Read timed out

**Comment by omaRaad** [comment]
@duff627 I really can't help without at least steps to reproduce or a reproducible project
